"""The hole migration (FR-0087, DEC-0073) -- measured on real documents and a real store.

WHAT THIS FILE HOLDS. `tools/migrate_holes.py` is the ONE run that turns the H-numbered section of
`docs/POST_V2_WISHLIST.md` into typed items and leaves a generated pointer index behind. Every
test here drives the shipped module against a state directory the KERNEL wrote, over a document
written for the case -- never by handing its functions a dictionary, because what has to hold is
what a run does to a store.

WHAT IT DELIBERATELY DOES NOT RE-MEASURE: the judges that read the migrated items live in
`.claude/hooks/test_gates.py` (they are gate-suite tests and run with `python -B -m pytest
.claude/hooks/test_gates.py`), and the door itself is `tools/test_state.py`'s subject.
"""
import io
import json
import os
import subprocess
import sys

import pytest

import conftest

ROOT = conftest.ROOT
TEAM_KITS = conftest.TEAM_KITS

sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, TEAM_KITS)
import migrate_holes  # noqa: E402
from kernel.backlog_types import (  # noqa: E402
    AUTOMATA,
    HOLE_LIMIT_FIELD,
    HOLE_NUMBER_FIELD,
    HOLE_TEST_FIELD,
)
from kernel.state import ProjectState  # noqa: E402

PR_FIELDS = {"title": "The workbench", "class": "normal", "problem": "p", "goal": "g",
             "acceptance_criteria": [{"id": "AC-1", "text": "t"}], "invariants": [],
             "out_of_scope": [], "priority": "high", "user_story": "As the lead"}

DOCUMENT = """# A document

## 11. Something else

Prose that is not the hole list.

## 12. Loecherliste

| Eintrag | Stand | Was stattdessen begrenzt |
|---|---|---|
| H1 | **GESCHLOSSEN** (TSK-0001) | -- |
| H2 | **OFFEN** | nur die Aufmerksamkeit des Leads |
| H3 | **Ausnahme**, vom Nutzer abgenommen | die Rolle sagt es, kein Gate |

### H1 - Der erste Mechanismus - GESCHLOSSEN

**Mechanismus:** etwas war offen.

**Urteil: blockierend, geschlossen.** Rot ohne den Fix:
`tools/test_migrate_holes.py::test_a_second_run_over_the_same_document_writes_nothing`.

### H2 - Der zweite - OFFEN

**Mechanismus:** etwas ist noch offen.

**Urteil: offen.**

### H3 - Der dritte - benannte Ausnahme

**Mechanismus:** der Nutzer hat es abgenommen.

**Urteil: benannte Ausnahme.**

## 13. Danach

Mehr Prosa.
"""


def project(tmp_path, document=DOCUMENT):
    """A repo-shaped directory with a state the kernel wrote and a document to migrate."""
    repo = tmp_path / "repo"
    os.makedirs(str(repo / "project_memory"), exist_ok=True)
    os.makedirs(str(repo / "docs"), exist_ok=True)
    doc = str(repo / "docs" / "POST_V2_WISHLIST.md")
    io.open(doc, "w", encoding="utf-8", newline="\n").write(document)
    state = ProjectState(str(repo / "project_memory"))
    state.capture("PR", dict(PR_FIELDS))
    return str(repo), state, doc


def test_a_run_turns_every_entry_into_an_item_and_leaves_a_generated_index(tmp_path):
    """The whole point of FR-0087, measured end to end on a document with all three outcomes.

    THE VERDICT BECOMES THE STATUS -- a closed entry is VERIFIED and archived, an accepted
    exception is `ACCEPTED_EXCEPTION`, an open one is TRIAGED and stays where a reader looks for
    open work. THE LIMIT BECOMES A FIELD, and the entry's own prose becomes a file the item points
    at, because three of the shipped entries are larger than an active item may be.
    """
    repo, state, doc = project(tmp_path)
    report = migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    assert len(report["written"]) == 3 and len(report["prose"]) == 3, report

    holes = {str(item.get(HOLE_NUMBER_FIELD)): item
             for item in state._iter_every_stored_item()
             if item.get(HOLE_NUMBER_FIELD)}
    assert sorted(holes) == ["H1", "H2", "H3"], sorted(holes)
    assert holes["H1"]["status"] == "VERIFIED"
    assert holes["H2"]["status"] == "TRIAGED"
    assert holes["H3"]["status"] == "ACCEPTED_EXCEPTION"
    assert holes["H3"][HOLE_LIMIT_FIELD] == "die Rolle sagt es, kein Gate"
    assert HOLE_TEST_FIELD in holes["H1"], "the closed entry's cited test did not travel"

    # ...the prose left the document and is where the item says it is
    for number, item in holes.items():
        prose = os.path.join(repo, str(item["source"]).replace("/", os.sep))
        assert os.path.isfile(prose), (number, item["source"])
        assert "Mechanismus" in io.open(prose, encoding="utf-8").read()

    text = io.open(doc, encoding="utf-8").read()
    assert "### H1" not in text, "an entry stayed in the document beside its item"
    assert "GENERATED by tools/migrate_holes.py" in text
    for number in holes:
        assert "[%s](docs/holes/%s.md)" % (number, number) in text, number
    assert "## 11." in text and "## 13. Danach" in text, "the migration ate a neighbouring section"


def test_a_second_run_over_the_same_document_writes_nothing(tmp_path):
    """Idempotence is a property of the STORE, not of a marker file.

    `state.hole_by_number` is what decides it, so a run interrupted halfway resumes and a run over
    an already migrated document is a no-op WITH A ZERO EXIT -- which it was not at first: an
    earlier cut also refused when a verdict word of the map appeared in no row, and the second run
    (whose document has no rows left at all) exited 1. That reading would also have refused a merge
    patch bringing three new entries, which is the run this script exists for.
    """
    _repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    before = io.open(doc, "rb").read()
    before_items = sorted(item["id"] for item in state._iter_every_stored_item())

    again = migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    assert again["written"] == [] and again["prose"] == [], again
    assert io.open(doc, "rb").read() == before, "the second run rewrote the document"
    assert sorted(item["id"] for item in state._iter_every_stored_item()) == before_items


def test_an_entry_that_arrives_later_is_migrated_with_the_number_it_was_reserved_under(tmp_path):
    """How the other streams' holes reach the store: in TODAY's format, out of a merge patch.

    A generation cuts several streams and each files what it measured as an `### H<n>` entry plus a
    summary row. Such a patch lands in a document that is ALREADY an index, so the run has to take
    a section carrying both -- and it has to keep the number the stream reserved in its own item,
    or every citation of it in that stream's protocol points at nothing.
    """
    _repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    arriving = io.open(doc, encoding="utf-8").read().replace(
        "| Loch | Item | Stand | Titel |",
        "| H157 | **OFFEN** | der Lead liest es |\n\n| Loch | Item | Stand | Titel |")
    arriving = arriving.replace(
        "## 13. Danach",
        "### H157 - Ein Loch aus einem anderen Strom - OFFEN\n\n"
        "**Mechanismus:** im Merge angekommen.\n\n**Urteil: offen.**\n\n## 13. Danach")
    io.open(doc, "w", encoding="utf-8", newline="\n").write(arriving)

    report = migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    assert [name for name, _id, _status in report["written"]] == ["H157"], report
    numbers = {str(item.get(HOLE_NUMBER_FIELD)) for item in state._iter_every_stored_item()
               if item.get(HOLE_NUMBER_FIELD)}
    assert numbers == {"H1", "H2", "H3", "H157"}, numbers
    assert "[H157](docs/holes/H157.md)" in io.open(doc, encoding="utf-8").read()


def test_a_verdict_the_map_does_not_know_is_refused_rather_than_guessed(tmp_path):
    """A status this run cannot read off the document is a status it must not invent.

    The whole store keeps whatever this writes, and an item is practically immutable -- so a
    guessed verdict is a lie nothing later repairs. Refusing is the only honest answer, and the
    refusal names the word.
    """
    _repo, state, doc = project(tmp_path, DOCUMENT.replace("| H2 | **OFFEN** |",
                                                           "| H2 | **VIELLEICHT** |"))
    with pytest.raises(SystemExit) as refusal:
        migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    assert "vielleicht" in str(refusal.value), refusal.value
    assert not [item for item in state._iter_every_stored_item()
                if item.get(HOLE_NUMBER_FIELD)], "it wrote before it refused"


def test_every_verdict_the_migration_reads_maps_onto_the_bug_automaton():
    """Both ends of `VERDICT_STATUS` against something that cannot go stale.

    NOT against the shipped document: after the migration that document carries no rows at all, so
    a test comparing the map with it would measure nothing -- and a test that cannot fail is
    dearer than no test. What CAN go stale is the other side: a renamed or dropped `BUG` status
    turns a row of this map into a write the kernel refuses, and a severity outside the vocabulary
    the shipped items use turns every migrated hole into a record nobody can sort.
    """
    automaton = AUTOMATA["BUG"]
    for word, (status, severity) in sorted(migrate_holes.VERDICT_STATUS.items()):
        assert status in automaton.states, (word, status)
        assert severity in ("low", "medium", "high", "critical"), (word, severity)
    produced = {status for status, _severity in migrate_holes.VERDICT_STATUS.values()}
    assert produced & automaton.terminals, "no verdict of this map closes a hole at all"
    assert produced - automaton.terminals, "no verdict of this map leaves a hole open at all"


def test_the_generated_index_is_rendered_from_the_store_and_not_from_the_document(tmp_path):
    """The index is a VIEW of the items -- so a hole the store gains shows up without an edit.

    Measured by adding one through the ordinary capture route (`state.capture(hole=True)`, which
    allocates the number) and re-rendering: the row appears, and its number is the one the kernel
    handed out rather than one this test chose.
    """
    _repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    before = migrate_holes.render_index(state)

    fresh = state.capture("BUG", {
        "title": "a gap measured after the migration", "related_pr": "PR-0001",
        "observed": "measured today", "expected": "closed", "repro": "run it", "severity": "low",
        "acceptance_criteria": [{"id": "AC-1", "text": "closed"}],
        HOLE_LIMIT_FIELD: "nothing yet"}, hole=True)
    # the number is the kernel's max-scan over the three the document brought, not one this test
    # chose -- which is the whole property `capture(hole=True)` carries
    assert fresh[HOLE_NUMBER_FIELD] == "H4", fresh[HOLE_NUMBER_FIELD]

    after = migrate_holes.render_index(state)
    assert len(after) == len(before) + 1
    assert any(fresh["id"] in line and "H4" in line for line in after), after[-3:]


# -- what the round-1 verification measured as missing (F2, F3, F4) ------------

def _kernel_cli(repo, *argv, timeout=120):
    """Run the shipped command surface as a PROCESS -- the way a role reaches it."""
    env = dict(os.environ, PYTHONPATH=TEAM_KITS, PYTHONDONTWRITEBYTECODE="1")
    return subprocess.run(
        [sys.executable, "-B", "-m", "kernel.cli", "--root", "project_memory", *argv],
        cwd=repo, capture_output=True, text=True, env=env, timeout=timeout)


def test_the_kernel_command_migrates_the_holes_and_is_idempotent(tmp_path):
    """The ONE writing run on the route gate 1 sanctions, driven as a process.

    WHY IT IS A KERNEL COMMAND (TSK-0126, merge rework 3): the migration writes canonical state,
    and canonical state has one writer -- `python -B -m kernel.cli --root project_memory
    <command>`. Handing the run to a user for a shell outside Claude Code is a route a REMOTE user
    does not have, so the lead's one line has to be takeable inside a session.

    THE SAME DOOR, not a second one: `tools/migrate_holes.py` calls `kernel.holes` too, which is
    what keeps "two spellings, one behaviour" from being a claim. Measured here through the kernel
    surface only -- the tool's own line is measured by every other node of this file.

    Three properties in one run, because they are one story: without `--apply` nothing is written,
    with it every entry becomes an item and a prose file, and a second run writes nothing.
    """
    repo, state, doc = project(tmp_path)
    before = io.open(doc, encoding="utf-8").read()

    dry = _kernel_cli(repo, "migrate-holes", "--related-pr", "PR-0001")
    assert dry.returncode == 0, dry.stdout + dry.stderr
    assert "3 written" in dry.stdout, dry.stdout
    assert io.open(doc, encoding="utf-8").read() == before, "the dry run wrote the document"
    assert not state.hole_by_number("H1"), "the dry run wrote an item"

    applied = _kernel_cli(repo, "migrate-holes", "--related-pr", "PR-0001", "--apply")
    assert applied.returncode == 0, applied.stdout + applied.stderr
    assert "3 written" in applied.stdout, applied.stdout
    assert state.hole_by_number("H1"), "the writing run left no item"
    assert os.path.isfile(os.path.join(repo, "docs", "holes", "H1.md")), "no prose file"
    after = io.open(doc, encoding="utf-8").read()
    assert "| [H1](docs/holes/H1.md)" in after, after[-400:]

    again = _kernel_cli(repo, "migrate-holes", "--related-pr", "PR-0001", "--apply")
    assert again.returncode == 0, again.stdout + again.stderr
    assert "0 written" in again.stdout, again.stdout
    assert io.open(doc, encoding="utf-8").read() == after, "the second run moved the document"


def test_the_kernel_command_asks_for_the_goal_unless_it_writes_no_item(tmp_path):
    """`--related-pr` is owed by every shape that writes an item, and by no other.

    An item hangs from a goal; `--reindex` writes the pointer index and nothing else, so it is the
    one shape with nothing to hang. Both directions, because a command that demanded the flag
    everywhere would make the index unrepairable and one that demanded it nowhere would file items
    under nothing.
    """
    repo, _state, _doc = project(tmp_path)
    refused = _kernel_cli(repo, "migrate-holes", "--apply")
    assert refused.returncode == 2, refused.stdout + refused.stderr
    assert "--related-pr" in refused.stderr, refused.stderr

    assert _kernel_cli(repo, "migrate-holes", "--related-pr", "PR-0001",
                       "--apply").returncode == 0
    reindexed = _kernel_cli(repo, "migrate-holes", "--reindex")
    assert reindexed.returncode == 0, reindexed.stdout + reindexed.stderr
    assert "index rewritten from the store" in reindexed.stdout, reindexed.stdout


def test_a_new_hole_can_be_filed_from_the_command_surface(tmp_path):
    """F2: there has to be a way to file a NEW hole that is not a hand-numbered heading.

    MEASURED before this existed: the generated index told every reader that new numbers come from
    `capture --hole`, and the shipped parser answered `unrecognized arguments: --hole`. So the only
    working route for a new gap was the `### H<n>` entry with a number chosen by hand -- the very
    defect FR-0087 was written against, restated by a document this migration generates.

    DRIVEN AS A PROCESS, because what has to hold is that a ROLE can type it: the flag, the body on
    stdin, the number in the output, and the number chosen by the kernel and not by the caller.
    """
    repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)

    body = json.dumps({"title": "a gap measured today", "related_pr": "PR-0001",
                       "observed": "the chain runs", "expected": "it should not",
                       "repro": "run it", "severity": "low",
                       "acceptance_criteria": [{"id": "AC-1", "text": "closed or accepted"}],
                       HOLE_LIMIT_FIELD: "the role says so, no gate"})
    env = dict(os.environ, PYTHONPATH=TEAM_KITS, PYTHONDONTWRITEBYTECODE="1")
    result = subprocess.run(
        [sys.executable, "-B", "-m", "kernel.cli", "--root", "project_memory",
         "capture", "BUG", "--hole"],
        cwd=repo, input=body, capture_output=True, text=True, env=env, timeout=120)
    assert result.returncode == 0, result.stdout + result.stderr
    assert "H4" in result.stdout, result.stdout
    assert "--reindex" in result.stderr, (
        "the caller is not told how the index catches up: %r" % result.stderr)

    filed = [item for item in state._iter_every_stored_item()
             if str(item.get(HOLE_NUMBER_FIELD) or "") == "H4"]
    assert len(filed) == 1 and filed[0]["title"] == "a gap measured today"

    # ...and the number is the kernel's: a caller that tries to choose one is refused
    refused = subprocess.run(
        [sys.executable, "-B", "-m", "kernel.cli", "--root", "project_memory",
         "capture", "BUG", "--hole"],
        cwd=repo, input=json.dumps(json.loads(body) | {HOLE_NUMBER_FIELD: "H99"}),
        capture_output=True, text=True, env=env, timeout=120)
    assert refused.returncode != 0 and HOLE_NUMBER_FIELD in refused.stderr, refused.stderr


def test_a_hole_captured_after_the_migration_reaches_the_generated_index(tmp_path):
    """F3: the index is a VIEW of the store, so it has to be rewritable from the store alone.

    MEASURED before this was fixed: the rewrite of the section sat behind the entry loop, and after
    the one-time migration that loop is empty -- so a hole captured through the kernel was missing
    from the index, the gate test went permanently red, and the remedy that test prints (`re-run
    this with --apply`) changed nothing. Index != generated, before and after the remedy.

    BOTH ROUTES ARE MEASURED, because both are printed to a reader: `--apply` over a document with
    no entries left, and the `--reindex` the capture surface names.

    WHAT IT ASKS OF THE ROW is that the NUMBER and the ITEM are in it, not that the number is a
    link: only the migration writes a prose file, so a hole captured afterwards has none and is
    rendered unlinked (`_prose_link`, and `test_a_hole_with_no_prose_file_is_a_row_without_a_link`
    is that rule's own measurement). Until 2026-09-05 this line asked for the link, and the shipped
    document carried nine rows pointing at files nobody had written.
    """
    repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    fresh = state.capture("BUG", {
        "title": "a gap measured after the migration", "related_pr": "PR-0001",
        "observed": "measured today", "expected": "closed", "repro": "run it", "severity": "low",
        "acceptance_criteria": [{"id": "AC-1", "text": "closed"}],
        HOLE_LIMIT_FIELD: "nothing yet"}, hole=True)
    assert fresh[HOLE_NUMBER_FIELD] not in io.open(doc, encoding="utf-8").read()

    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    text = io.open(doc, encoding="utf-8").read()
    assert "| %s | %s |" % (fresh[HOLE_NUMBER_FIELD], fresh["id"]) in text, text[-400:]
    lines, start, end = migrate_holes.read_section(doc)
    assert lines[start:end] == migrate_holes.render_index(state)

    # ...and the flag the capture surface points at does the same thing on its own
    io.open(doc, "w", encoding="utf-8", newline="\n").write(
        text.replace("| %s |" % fresh[HOLE_NUMBER_FIELD], "| H999 |", 1))
    result = _kernel_reindex(repo)
    assert result.returncode == 0, result.stdout + result.stderr
    lines, start, end = migrate_holes.read_section(doc)
    assert lines[start:end] == migrate_holes.render_index(state), "the reindex did not restore it"


def _kernel_reindex(repo):
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    return subprocess.run(
        [sys.executable, "-B", os.path.join(ROOT, "tools", "migrate_holes.py"),
         "--root", "project_memory", "--doc", os.path.join(repo, "docs",
                                                           "POST_V2_WISHLIST.md"),
         "--reindex"],
        cwd=repo, capture_output=True, text=True, env=env, timeout=120)


def test_a_number_collision_at_the_merge_is_refused_not_skipped(tmp_path):
    """F4: an existing number is a RESUMPTION only when it is the same entry.

    THE SITUATION IS THE MERGE ITSELF, not a corner case: four streams reserve their numbers by
    hand in their own items, and two of them can pick the same one. MEASURED before this refusal:
    the store carried H151, the document brought a DIFFERENT H151 in the current format, and the
    run answered `0 written, 1 already in the store` with rc 0 -- no item, no prose file, and the
    rewrite of the section removed the entry from the document. Silent data loss on the one run
    the whole migration rests on.

    AND THE RESUMPTION CASE STAYS OPEN, which is the other end: the same entry met twice is still
    a no-op, so an interrupted run resumes.
    """
    _repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    before = sorted(item["id"] for item in state._iter_every_stored_item())

    collision = io.open(doc, encoding="utf-8").read().replace(
        "| Loch | Item | Stand | Titel |",
        "| H1 | **OFFEN** | ein anderer Strom liest es |\n\n| Loch | Item | Stand | Titel |")
    collision = collision.replace(
        "## 13. Danach",
        "### H1 - Ein ANDERER Eintrag unter derselben Nummer - OFFEN\n\n"
        "**Mechanismus:** zwei Stroeme haben dieselbe Nummer reserviert.\n\n"
        "**Urteil: offen.**\n\n## 13. Danach")
    io.open(doc, "w", encoding="utf-8", newline="\n").write(collision)

    with pytest.raises(SystemExit) as refusal:
        migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    message = str(refusal.value)
    assert "H1" in message and "different" in message.lower(), message
    assert "title" in message, "the refusal does not say what differs: %s" % message
    assert sorted(item["id"] for item in state._iter_every_stored_item()) == before, (
        "it wrote something before refusing")
    assert "### H1 - Ein ANDERER" in io.open(doc, encoding="utf-8").read(), (
        "the refused entry was removed from the document anyway -- that is the data loss")


def test_only_a_hole_can_be_filed_as_one_from_the_command_surface(tmp_path):
    """R1 of the round-2 verification: the type check was an enumeration of ONE.

    MEASURED before this was bound to the definition: the only type check was `!= "TSK"`, so
    `capture FR --hole` answered rc 0 `FR-0001 OPEN H3` and `capture DEC --hole` answered rc 0
    `DEC-0001 VALID H4`. Against a migrated store that burnt a hole number nothing can free, left
    `test_every_hole_states_a_verdict_and_an_unclosed_one_names_its_limit` permanently red ("stands
    in 'VALID', which is no status of its type") and would have written the decision into the
    shipped document as a hole. No kernel command deletes an item and `project_memory/` takes no
    tool write, so the repair needs a shell outside the session.

    DRIVEN AS A PROCESS over TWO other types, and the refusal is asked of the KERNEL: a check that
    lived in the parser would be a second spelling of a definition that is right beside it.
    """
    repo, state, _doc = project(tmp_path)
    env = dict(os.environ, PYTHONPATH=TEAM_KITS, PYTHONDONTWRITEBYTECODE="1")

    def capture(item_type, payload):
        return subprocess.run(
            [sys.executable, "-B", "-m", "kernel.cli", "--root", "project_memory",
             "capture", item_type, "--hole"],
            cwd=repo, input=json.dumps(payload), capture_output=True, text=True, env=env,
            timeout=120)

    wish = capture("FR", {"title": "a wish", "request_text": "please"})
    assert wish.returncode != 0, wish.stdout + wish.stderr
    assert "a hole is a BUG" in wish.stderr, wish.stderr

    decision = capture("DEC", {"title": "a decision", "context": "c", "decision": "d",
                               "consequences": "x", "source": "s", "work": "none"})
    assert decision.returncode != 0, decision.stdout + decision.stderr

    # ...and a work order, which never reaches `state.capture` at all. THE TEXT AND THE STORE ARE
    # BOTH ASSERTED, and the round-3 verification is why: with the CLI check removed this line read
    # `returncode != 0` and stayed green, while what really happened was that the ORDER WAS WRITTEN,
    # the flag was silently ignored, and the non-zero exit came from an uncaught `KeyError` further
    # down. A refusal and a crash are not the same answer, and only one of them leaves the store
    # alone.
    order = capture("TSK", dict(TSK_FIELDS_FOR_HOLE_TEST))
    assert order.returncode != 0, order.stdout + order.stderr
    assert "a hole is a BUG" in order.stderr, (
        "the work order was not REFUSED -- this is some other non-zero exit: %s" % order.stderr)
    assert not list(state.iter_active_items("TSK")), (
        "the refused work order was written anyway")

    assert not [item for item in state._iter_every_stored_item()
                if item.get(HOLE_NUMBER_FIELD)], "a number was burnt on a refused capture"
    assert state.next_hole_number() == "H1"


TSK_FIELDS_FOR_HOLE_TEST = {
    "product_requirement": "PR-0001", "derives_from": "PR-0001", "type": "implementation",
    "assigned_role": "backend-developer", "acceptance_refs": ["AC-1"], "required_inputs": [],
    "allowed_scope": ["src/**"], "forbidden_scope": [], "expected_outputs": ["out"], "dependencies": []}


def test_an_empty_store_does_not_empty_a_full_index(tmp_path):
    """R2 of the round-2 verification: a mistyped `--root` cost the index and said it succeeded.

    MEASURED before this refusal: `--reindex` against an EMPTY state directory, over a document
    carrying 143 pointer rows, answered "index rewritten from the store: 0 hole(s)" with rc 0 and
    left a section with no rows at all. That is the same class as the number collision -- a loss
    the run reports as a success.

    THE REFUSAL IS NARROW ON PURPOSE, and the other end is measured here too: an index that shrinks
    because a hole was ARCHIVED out of the active store is a legitimate rewrite and still goes
    through. What is refused is the one case where the new index is empty and the old one is not.

    AND IT COUNTS UNLINKED ROWS, which is why the prose file of one hole is removed below before
    the refusal is asked for. A row is only linked where its prose file exists (`_prose_link`), so
    a reader that counted `| [H<n>](` rows would read a document of freshly captured holes as empty
    and let the very loss through that this refusal exists for.
    """
    repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    os.remove(os.path.join(repo, "docs", "holes", "H2.md"))
    lines, start, end = migrate_holes.read_section(doc)
    migrate_holes._write_index(doc, lines, start, end, state, migrate_holes.DEFAULT_HOLES_DIR)
    full = io.open(doc, "rb").read()
    assert b"| H2 |" in full and b"[H2](" not in full, "the premise of the unlinked row is gone"
    assert migrate_holes._index_row_count(
        migrate_holes.read_section(doc)[0][slice(*migrate_holes.read_section(doc)[1:])]) == 3

    empty_root = tmp_path / "elsewhere" / "project_memory"
    os.makedirs(str(empty_root))
    from kernel.state import ProjectState
    empty = ProjectState(str(empty_root))
    lines, start, end = migrate_holes.read_section(doc)
    with pytest.raises(SystemExit) as refusal:
        migrate_holes._write_index(doc, lines, start, end, empty, migrate_holes.DEFAULT_HOLES_DIR)
    assert "carries no hole at all" in str(refusal.value), refusal.value
    assert io.open(doc, "rb").read() == full, "it wrote before refusing"

    # ...and a store that shrank honestly is still written
    holes = [item for item in state._iter_every_stored_item() if item.get(HOLE_NUMBER_FIELD)]
    victim = next(item for item in holes if item.get("status") == "TRIAGED")
    state.transition(victim["id"], "REJECTED")
    state.archive(victim["id"])
    lines, start, end = migrate_holes.read_section(doc)
    migrate_holes._write_index(doc, lines, start, end, state, migrate_holes.DEFAULT_HOLES_DIR)
    lines, start, end = migrate_holes.read_section(doc)
    assert migrate_holes._index_row_count(lines[start:end]) == 3, (
        "an archived hole keeps its row -- the index reads the whole store")


def test_a_hole_with_no_prose_file_is_a_row_without_a_link(tmp_path):
    """The index links a number only where the prose file behind it EXISTS.

    THE MEASURED DEFECT (2026-09-05, this repository's own document): only `migrate` writes a file
    under `docs/holes/`; `capture --hole` writes an item and nothing else. The renderer linked every
    row regardless, so from the first hole captured after the one-time migration the shipped index
    pointed at nine files that had never been written (H166-H173). A pointer nobody can follow is
    the class this repo keeps paying for, and the index is what a human opens.

    BOTH DIRECTIONS, on ONE store, so neither half can be satisfied by the other: the migrated hole
    keeps its link, the captured one loses it, and deleting the migrated hole's file takes its link
    away on the next render -- the renderer asks the filesystem, it does not remember.
    """
    repo, state, doc = project(tmp_path)
    migrate_holes.migrate(state, doc, "PR-0001", apply=True)
    captured = state.capture("BUG", {
        "title": "measured after the migration", "related_pr": "PR-0001", "observed": "o",
        "expected": "e", "repro": "r", "severity": "low",
        "acceptance_criteria": [{"id": "AC-1", "text": "t"}], HOLE_LIMIT_FIELD: "the lead reads it",
    }, hole=True)
    number = str(captured[HOLE_NUMBER_FIELD])
    assert not os.path.isfile(os.path.join(repo, "docs", "holes", number + ".md")), (
        "the capture door wrote a prose file after all -- this test's premise is gone")

    migrate_holes.reindex(state, doc)
    text = io.open(doc, encoding="utf-8").read()
    assert "| [H1](docs/holes/H1.md) |" in text, "the migrated hole lost its link"
    assert "| %s | %s |" % (number, captured["id"]) in text, text[-500:]
    assert "docs/holes/%s.md" % number not in text, (
        "the row links at a prose file nobody wrote: %s" % number)

    os.remove(os.path.join(repo, "docs", "holes", "H1.md"))
    migrate_holes.reindex(state, doc)
    text = io.open(doc, encoding="utf-8").read()
    assert "docs/holes/H1.md" not in text, "the link outlived the file it points at"
    assert "| H1 |" in text, text[-500:]
